// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class AddStakingToken extends ethereum.Event {
  get params(): AddStakingToken__Params {
    return new AddStakingToken__Params(this);
  }
}

export class AddStakingToken__Params {
  _event: AddStakingToken;

  constructor(event: AddStakingToken) {
    this._event = event;
  }

  get token(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class BalanceDecreased extends ethereum.Event {
  get params(): BalanceDecreased__Params {
    return new BalanceDecreased__Params(this);
  }
}

export class BalanceDecreased__Params {
  _event: BalanceDecreased;

  constructor(event: BalanceDecreased) {
    this._event = event;
  }

  get token(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class Upgraded extends ethereum.Event {
  get params(): Upgraded__Params {
    return new Upgraded__Params(this);
  }
}

export class Upgraded__Params {
  _event: Upgraded;

  constructor(event: Upgraded) {
    this._event = event;
  }

  get implementation(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class BalanceIncreased extends ethereum.Event {
  get params(): BalanceIncreased__Params {
    return new BalanceIncreased__Params(this);
  }
}

export class BalanceIncreased__Params {
  _event: BalanceIncreased;

  constructor(event: BalanceIncreased) {
    this._event = event;
  }

  get token(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class ClaimRewards extends ethereum.Event {
  get params(): ClaimRewards__Params {
    return new ClaimRewards__Params(this);
  }
}

export class ClaimRewards__Params {
  _event: ClaimRewards;

  constructor(event: ClaimRewards) {
    this._event = event;
  }

  get account(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get token(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get reward(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get recepient(): Address {
    return this._event.parameters[4].value.toAddress();
  }
}

export class ContractInitialized extends ethereum.Event {
  get params(): ContractInitialized__Params {
    return new ContractInitialized__Params(this);
  }
}

export class ContractInitialized__Params {
  _event: ContractInitialized;

  constructor(event: ContractInitialized) {
    this._event = event;
  }

  get controller(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get ts(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get block(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class Deposit extends ethereum.Event {
  get params(): Deposit__Params {
    return new Deposit__Params(this);
  }
}

export class Deposit__Params {
  _event: Deposit;

  constructor(event: Deposit) {
    this._event = event;
  }

  get stakingToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class Initialized extends ethereum.Event {
  get params(): Initialized__Params {
    return new Initialized__Params(this);
  }
}

export class Initialized__Params {
  _event: Initialized;

  constructor(event: Initialized) {
    this._event = event;
  }

  get version(): i32 {
    return this._event.parameters[0].value.toI32();
  }
}

export class NotifyReward extends ethereum.Event {
  get params(): NotifyReward__Params {
    return new NotifyReward__Params(this);
  }
}

export class NotifyReward__Params {
  _event: NotifyReward;

  constructor(event: NotifyReward) {
    this._event = event;
  }

  get from(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get token(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get reward(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }
}

export class RevisionIncreased extends ethereum.Event {
  get params(): RevisionIncreased__Params {
    return new RevisionIncreased__Params(this);
  }
}

export class RevisionIncreased__Params {
  _event: RevisionIncreased;

  constructor(event: RevisionIncreased) {
    this._event = event;
  }

  get value(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get oldLogic(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class VeTokenLocked extends ethereum.Event {
  get params(): VeTokenLocked__Params {
    return new VeTokenLocked__Params(this);
  }
}

export class VeTokenLocked__Params {
  _event: VeTokenLocked;

  constructor(event: VeTokenLocked) {
    this._event = event;
  }

  get stakingToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get tokenId(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class VeTokenUnlocked extends ethereum.Event {
  get params(): VeTokenUnlocked__Params {
    return new VeTokenUnlocked__Params(this);
  }
}

export class VeTokenUnlocked__Params {
  _event: VeTokenUnlocked;

  constructor(event: VeTokenUnlocked) {
    this._event = event;
  }

  get stakingToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get tokenId(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class Withdraw extends ethereum.Event {
  get params(): Withdraw__Params {
    return new Withdraw__Params(this);
  }
}

export class Withdraw__Params {
  _event: Withdraw;

  constructor(event: Withdraw) {
    this._event = event;
  }

  get stakingToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get full(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get veId(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }
}

export class MultiGaugeAbi extends ethereum.SmartContract {
  static bind(address: Address): MultiGaugeAbi {
    return new MultiGaugeAbi("MultiGaugeAbi", address);
  }

  CONTROLLABLE_VERSION(): string {
    let result = super.call(
      "CONTROLLABLE_VERSION",
      "CONTROLLABLE_VERSION():(string)",
      []
    );

    return result[0].toString();
  }

  try_CONTROLLABLE_VERSION(): ethereum.CallResult<string> {
    let result = super.tryCall(
      "CONTROLLABLE_VERSION",
      "CONTROLLABLE_VERSION():(string)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  MULTI_GAUGE_VERSION(): string {
    let result = super.call(
      "MULTI_GAUGE_VERSION",
      "MULTI_GAUGE_VERSION():(string)",
      []
    );

    return result[0].toString();
  }

  try_MULTI_GAUGE_VERSION(): ethereum.CallResult<string> {
    let result = super.tryCall(
      "MULTI_GAUGE_VERSION",
      "MULTI_GAUGE_VERSION():(string)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  MULTI_POOL_VERSION(): string {
    let result = super.call(
      "MULTI_POOL_VERSION",
      "MULTI_POOL_VERSION():(string)",
      []
    );

    return result[0].toString();
  }

  try_MULTI_POOL_VERSION(): ethereum.CallResult<string> {
    let result = super.tryCall(
      "MULTI_POOL_VERSION",
      "MULTI_POOL_VERSION():(string)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  balanceOf(param0: Address, param1: Address): BigInt {
    let result = super.call(
      "balanceOf",
      "balanceOf(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBigInt();
  }

  try_balanceOf(param0: Address, param1: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "balanceOf",
      "balanceOf(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  controller(): Address {
    let result = super.call("controller", "controller():(address)", []);

    return result[0].toAddress();
  }

  try_controller(): ethereum.CallResult<Address> {
    let result = super.tryCall("controller", "controller():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  created(): BigInt {
    let result = super.call("created", "created():(uint256)", []);

    return result[0].toBigInt();
  }

  try_created(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("created", "created():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  createdBlock(): BigInt {
    let result = super.call("createdBlock", "createdBlock():(uint256)", []);

    return result[0].toBigInt();
  }

  try_createdBlock(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("createdBlock", "createdBlock():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  defaultRewardToken(): Address {
    let result = super.call(
      "defaultRewardToken",
      "defaultRewardToken():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_defaultRewardToken(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "defaultRewardToken",
      "defaultRewardToken():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  derivedBalance(stakingToken: Address, account: Address): BigInt {
    let result = super.call(
      "derivedBalance",
      "derivedBalance(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(account)
      ]
    );

    return result[0].toBigInt();
  }

  try_derivedBalance(
    stakingToken: Address,
    account: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "derivedBalance",
      "derivedBalance(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(account)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  derivedBalances(param0: Address, param1: Address): BigInt {
    let result = super.call(
      "derivedBalances",
      "derivedBalances(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBigInt();
  }

  try_derivedBalances(
    param0: Address,
    param1: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "derivedBalances",
      "derivedBalances(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  derivedSupply(param0: Address): BigInt {
    let result = super.call(
      "derivedSupply",
      "derivedSupply(address):(uint256)",
      [ethereum.Value.fromAddress(param0)]
    );

    return result[0].toBigInt();
  }

  try_derivedSupply(param0: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "derivedSupply",
      "derivedSupply(address):(uint256)",
      [ethereum.Value.fromAddress(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  duration(): BigInt {
    let result = super.call("duration", "duration():(uint256)", []);

    return result[0].toBigInt();
  }

  try_duration(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("duration", "duration():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  earned(
    stakingToken: Address,
    rewardToken: Address,
    account: Address
  ): BigInt {
    let result = super.call(
      "earned",
      "earned(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(account)
      ]
    );

    return result[0].toBigInt();
  }

  try_earned(
    stakingToken: Address,
    rewardToken: Address,
    account: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "earned",
      "earned(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(rewardToken),
        ethereum.Value.fromAddress(account)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  isController(_value: Address): boolean {
    let result = super.call("isController", "isController(address):(bool)", [
      ethereum.Value.fromAddress(_value)
    ]);

    return result[0].toBoolean();
  }

  try_isController(_value: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("isController", "isController(address):(bool)", [
      ethereum.Value.fromAddress(_value)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  isGovernance(_value: Address): boolean {
    let result = super.call("isGovernance", "isGovernance(address):(bool)", [
      ethereum.Value.fromAddress(_value)
    ]);

    return result[0].toBoolean();
  }

  try_isGovernance(_value: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("isGovernance", "isGovernance(address):(bool)", [
      ethereum.Value.fromAddress(_value)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  isRewardToken(param0: Address, param1: Address): boolean {
    let result = super.call(
      "isRewardToken",
      "isRewardToken(address,address):(bool)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBoolean();
  }

  try_isRewardToken(
    param0: Address,
    param1: Address
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "isRewardToken",
      "isRewardToken(address,address):(bool)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  isStakeToken(token: Address): boolean {
    let result = super.call("isStakeToken", "isStakeToken(address):(bool)", [
      ethereum.Value.fromAddress(token)
    ]);

    return result[0].toBoolean();
  }

  try_isStakeToken(token: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("isStakeToken", "isStakeToken(address):(bool)", [
      ethereum.Value.fromAddress(token)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  lastTimeRewardApplicable(
    stakingToken: Address,
    rewardToken: Address
  ): BigInt {
    let result = super.call(
      "lastTimeRewardApplicable",
      "lastTimeRewardApplicable(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(rewardToken)
      ]
    );

    return result[0].toBigInt();
  }

  try_lastTimeRewardApplicable(
    stakingToken: Address,
    rewardToken: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "lastTimeRewardApplicable",
      "lastTimeRewardApplicable(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(rewardToken)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  lastUpdateTime(param0: Address, param1: Address): BigInt {
    let result = super.call(
      "lastUpdateTime",
      "lastUpdateTime(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBigInt();
  }

  try_lastUpdateTime(
    param0: Address,
    param1: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "lastUpdateTime",
      "lastUpdateTime(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  left(stakingToken: Address, rewardToken: Address): BigInt {
    let result = super.call("left", "left(address,address):(uint256)", [
      ethereum.Value.fromAddress(stakingToken),
      ethereum.Value.fromAddress(rewardToken)
    ]);

    return result[0].toBigInt();
  }

  try_left(
    stakingToken: Address,
    rewardToken: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall("left", "left(address,address):(uint256)", [
      ethereum.Value.fromAddress(stakingToken),
      ethereum.Value.fromAddress(rewardToken)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  periodFinish(param0: Address, param1: Address): BigInt {
    let result = super.call(
      "periodFinish",
      "periodFinish(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBigInt();
  }

  try_periodFinish(
    param0: Address,
    param1: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "periodFinish",
      "periodFinish(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  previousImplementation(): Address {
    let result = super.call(
      "previousImplementation",
      "previousImplementation():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_previousImplementation(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "previousImplementation",
      "previousImplementation():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  revision(): BigInt {
    let result = super.call("revision", "revision():(uint256)", []);

    return result[0].toBigInt();
  }

  try_revision(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("revision", "revision():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  rewardPerToken(stakingToken: Address, rewardToken: Address): BigInt {
    let result = super.call(
      "rewardPerToken",
      "rewardPerToken(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(rewardToken)
      ]
    );

    return result[0].toBigInt();
  }

  try_rewardPerToken(
    stakingToken: Address,
    rewardToken: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewardPerToken",
      "rewardPerToken(address,address):(uint256)",
      [
        ethereum.Value.fromAddress(stakingToken),
        ethereum.Value.fromAddress(rewardToken)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  rewardPerTokenStored(param0: Address, param1: Address): BigInt {
    let result = super.call(
      "rewardPerTokenStored",
      "rewardPerTokenStored(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBigInt();
  }

  try_rewardPerTokenStored(
    param0: Address,
    param1: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewardPerTokenStored",
      "rewardPerTokenStored(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  rewardRate(param0: Address, param1: Address): BigInt {
    let result = super.call(
      "rewardRate",
      "rewardRate(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );

    return result[0].toBigInt();
  }

  try_rewardRate(
    param0: Address,
    param1: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewardRate",
      "rewardRate(address,address):(uint256)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  rewardTokens(param0: Address, param1: BigInt): Address {
    let result = super.call(
      "rewardTokens",
      "rewardTokens(address,uint256):(address)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );

    return result[0].toAddress();
  }

  try_rewardTokens(
    param0: Address,
    param1: BigInt
  ): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "rewardTokens",
      "rewardTokens(address,uint256):(address)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  rewardTokensLength(token: Address): BigInt {
    let result = super.call(
      "rewardTokensLength",
      "rewardTokensLength(address):(uint256)",
      [ethereum.Value.fromAddress(token)]
    );

    return result[0].toBigInt();
  }

  try_rewardTokensLength(token: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewardTokensLength",
      "rewardTokensLength(address):(uint256)",
      [ethereum.Value.fromAddress(token)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  rewards(param0: Address, param1: Address, param2: Address): BigInt {
    let result = super.call(
      "rewards",
      "rewards(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromAddress(param2)
      ]
    );

    return result[0].toBigInt();
  }

  try_rewards(
    param0: Address,
    param1: Address,
    param2: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "rewards",
      "rewards(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromAddress(param2)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  rewardsRedirect(param0: Address): Address {
    let result = super.call(
      "rewardsRedirect",
      "rewardsRedirect(address):(address)",
      [ethereum.Value.fromAddress(param0)]
    );

    return result[0].toAddress();
  }

  try_rewardsRedirect(param0: Address): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "rewardsRedirect",
      "rewardsRedirect(address):(address)",
      [ethereum.Value.fromAddress(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  stakingTokens(param0: Address): boolean {
    let result = super.call("stakingTokens", "stakingTokens(address):(bool)", [
      ethereum.Value.fromAddress(param0)
    ]);

    return result[0].toBoolean();
  }

  try_stakingTokens(param0: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "stakingTokens",
      "stakingTokens(address):(bool)",
      [ethereum.Value.fromAddress(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  supportsInterface(interfaceId: Bytes): boolean {
    let result = super.call(
      "supportsInterface",
      "supportsInterface(bytes4):(bool)",
      [ethereum.Value.fromFixedBytes(interfaceId)]
    );

    return result[0].toBoolean();
  }

  try_supportsInterface(interfaceId: Bytes): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "supportsInterface",
      "supportsInterface(bytes4):(bool)",
      [ethereum.Value.fromFixedBytes(interfaceId)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  totalSupply(param0: Address): BigInt {
    let result = super.call("totalSupply", "totalSupply(address):(uint256)", [
      ethereum.Value.fromAddress(param0)
    ]);

    return result[0].toBigInt();
  }

  try_totalSupply(param0: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "totalSupply",
      "totalSupply(address):(uint256)",
      [ethereum.Value.fromAddress(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  userRewardPerTokenPaid(
    param0: Address,
    param1: Address,
    param2: Address
  ): BigInt {
    let result = super.call(
      "userRewardPerTokenPaid",
      "userRewardPerTokenPaid(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromAddress(param2)
      ]
    );

    return result[0].toBigInt();
  }

  try_userRewardPerTokenPaid(
    param0: Address,
    param1: Address,
    param2: Address
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "userRewardPerTokenPaid",
      "userRewardPerTokenPaid(address,address,address):(uint256)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromAddress(param1),
        ethereum.Value.fromAddress(param2)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  ve(): Address {
    let result = super.call("ve", "ve():(address)", []);

    return result[0].toAddress();
  }

  try_ve(): ethereum.CallResult<Address> {
    let result = super.tryCall("ve", "ve():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  veIds(param0: Address, param1: Address): BigInt {
    let result = super.call("veIds", "veIds(address,address):(uint256)", [
      ethereum.Value.fromAddress(param0),
      ethereum.Value.fromAddress(param1)
    ]);

    return result[0].toBigInt();
  }

  try_veIds(param0: Address, param1: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("veIds", "veIds(address,address):(uint256)", [
      ethereum.Value.fromAddress(param0),
      ethereum.Value.fromAddress(param1)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  voter(): Address {
    let result = super.call("voter", "voter():(address)", []);

    return result[0].toAddress();
  }

  try_voter(): ethereum.CallResult<Address> {
    let result = super.tryCall("voter", "voter():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class AddStakingTokenCall extends ethereum.Call {
  get inputs(): AddStakingTokenCall__Inputs {
    return new AddStakingTokenCall__Inputs(this);
  }

  get outputs(): AddStakingTokenCall__Outputs {
    return new AddStakingTokenCall__Outputs(this);
  }
}

export class AddStakingTokenCall__Inputs {
  _call: AddStakingTokenCall;

  constructor(call: AddStakingTokenCall) {
    this._call = call;
  }

  get token(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class AddStakingTokenCall__Outputs {
  _call: AddStakingTokenCall;

  constructor(call: AddStakingTokenCall) {
    this._call = call;
  }
}

export class AttachVeCall extends ethereum.Call {
  get inputs(): AttachVeCall__Inputs {
    return new AttachVeCall__Inputs(this);
  }

  get outputs(): AttachVeCall__Outputs {
    return new AttachVeCall__Outputs(this);
  }
}

export class AttachVeCall__Inputs {
  _call: AttachVeCall;

  constructor(call: AttachVeCall) {
    this._call = call;
  }

  get stakingToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get veId(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class AttachVeCall__Outputs {
  _call: AttachVeCall;

  constructor(call: AttachVeCall) {
    this._call = call;
  }
}

export class DetachVeCall extends ethereum.Call {
  get inputs(): DetachVeCall__Inputs {
    return new DetachVeCall__Inputs(this);
  }

  get outputs(): DetachVeCall__Outputs {
    return new DetachVeCall__Outputs(this);
  }
}

export class DetachVeCall__Inputs {
  _call: DetachVeCall;

  constructor(call: DetachVeCall) {
    this._call = call;
  }

  get stakingToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get veId(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class DetachVeCall__Outputs {
  _call: DetachVeCall;

  constructor(call: DetachVeCall) {
    this._call = call;
  }
}

export class GetAllRewardsCall extends ethereum.Call {
  get inputs(): GetAllRewardsCall__Inputs {
    return new GetAllRewardsCall__Inputs(this);
  }

  get outputs(): GetAllRewardsCall__Outputs {
    return new GetAllRewardsCall__Outputs(this);
  }
}

export class GetAllRewardsCall__Inputs {
  _call: GetAllRewardsCall;

  constructor(call: GetAllRewardsCall) {
    this._call = call;
  }

  get stakingToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class GetAllRewardsCall__Outputs {
  _call: GetAllRewardsCall;

  constructor(call: GetAllRewardsCall) {
    this._call = call;
  }
}

export class GetAllRewardsForTokensCall extends ethereum.Call {
  get inputs(): GetAllRewardsForTokensCall__Inputs {
    return new GetAllRewardsForTokensCall__Inputs(this);
  }

  get outputs(): GetAllRewardsForTokensCall__Outputs {
    return new GetAllRewardsForTokensCall__Outputs(this);
  }
}

export class GetAllRewardsForTokensCall__Inputs {
  _call: GetAllRewardsForTokensCall;

  constructor(call: GetAllRewardsForTokensCall) {
    this._call = call;
  }

  get _stakingTokens(): Array<Address> {
    return this._call.inputValues[0].value.toAddressArray();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class GetAllRewardsForTokensCall__Outputs {
  _call: GetAllRewardsForTokensCall;

  constructor(call: GetAllRewardsForTokensCall) {
    this._call = call;
  }
}

export class GetRewardCall extends ethereum.Call {
  get inputs(): GetRewardCall__Inputs {
    return new GetRewardCall__Inputs(this);
  }

  get outputs(): GetRewardCall__Outputs {
    return new GetRewardCall__Outputs(this);
  }
}

export class GetRewardCall__Inputs {
  _call: GetRewardCall;

  constructor(call: GetRewardCall) {
    this._call = call;
  }

  get stakingToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get tokens(): Array<Address> {
    return this._call.inputValues[2].value.toAddressArray();
  }
}

export class GetRewardCall__Outputs {
  _call: GetRewardCall;

  constructor(call: GetRewardCall) {
    this._call = call;
  }
}

export class HandleBalanceChangeCall extends ethereum.Call {
  get inputs(): HandleBalanceChangeCall__Inputs {
    return new HandleBalanceChangeCall__Inputs(this);
  }

  get outputs(): HandleBalanceChangeCall__Outputs {
    return new HandleBalanceChangeCall__Outputs(this);
  }
}

export class HandleBalanceChangeCall__Inputs {
  _call: HandleBalanceChangeCall;

  constructor(call: HandleBalanceChangeCall) {
    this._call = call;
  }

  get account(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class HandleBalanceChangeCall__Outputs {
  _call: HandleBalanceChangeCall;

  constructor(call: HandleBalanceChangeCall) {
    this._call = call;
  }
}

export class IncreaseRevisionCall extends ethereum.Call {
  get inputs(): IncreaseRevisionCall__Inputs {
    return new IncreaseRevisionCall__Inputs(this);
  }

  get outputs(): IncreaseRevisionCall__Outputs {
    return new IncreaseRevisionCall__Outputs(this);
  }
}

export class IncreaseRevisionCall__Inputs {
  _call: IncreaseRevisionCall;

  constructor(call: IncreaseRevisionCall) {
    this._call = call;
  }

  get oldLogic(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class IncreaseRevisionCall__Outputs {
  _call: IncreaseRevisionCall;

  constructor(call: IncreaseRevisionCall) {
    this._call = call;
  }
}

export class InitCall extends ethereum.Call {
  get inputs(): InitCall__Inputs {
    return new InitCall__Inputs(this);
  }

  get outputs(): InitCall__Outputs {
    return new InitCall__Outputs(this);
  }
}

export class InitCall__Inputs {
  _call: InitCall;

  constructor(call: InitCall) {
    this._call = call;
  }

  get controller_(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _ve(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _defaultRewardToken(): Address {
    return this._call.inputValues[2].value.toAddress();
  }
}

export class InitCall__Outputs {
  _call: InitCall;

  constructor(call: InitCall) {
    this._call = call;
  }
}

export class NotifyRewardAmountCall extends ethereum.Call {
  get inputs(): NotifyRewardAmountCall__Inputs {
    return new NotifyRewardAmountCall__Inputs(this);
  }

  get outputs(): NotifyRewardAmountCall__Outputs {
    return new NotifyRewardAmountCall__Outputs(this);
  }
}

export class NotifyRewardAmountCall__Inputs {
  _call: NotifyRewardAmountCall;

  constructor(call: NotifyRewardAmountCall) {
    this._call = call;
  }

  get stakingToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get token(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class NotifyRewardAmountCall__Outputs {
  _call: NotifyRewardAmountCall;

  constructor(call: NotifyRewardAmountCall) {
    this._call = call;
  }
}

export class RegisterRewardTokenCall extends ethereum.Call {
  get inputs(): RegisterRewardTokenCall__Inputs {
    return new RegisterRewardTokenCall__Inputs(this);
  }

  get outputs(): RegisterRewardTokenCall__Outputs {
    return new RegisterRewardTokenCall__Outputs(this);
  }
}

export class RegisterRewardTokenCall__Inputs {
  _call: RegisterRewardTokenCall;

  constructor(call: RegisterRewardTokenCall) {
    this._call = call;
  }

  get stakeToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get rewardToken(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class RegisterRewardTokenCall__Outputs {
  _call: RegisterRewardTokenCall;

  constructor(call: RegisterRewardTokenCall) {
    this._call = call;
  }
}

export class RemoveRewardTokenCall extends ethereum.Call {
  get inputs(): RemoveRewardTokenCall__Inputs {
    return new RemoveRewardTokenCall__Inputs(this);
  }

  get outputs(): RemoveRewardTokenCall__Outputs {
    return new RemoveRewardTokenCall__Outputs(this);
  }
}

export class RemoveRewardTokenCall__Inputs {
  _call: RemoveRewardTokenCall;

  constructor(call: RemoveRewardTokenCall) {
    this._call = call;
  }

  get stakeToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get rewardToken(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class RemoveRewardTokenCall__Outputs {
  _call: RemoveRewardTokenCall;

  constructor(call: RemoveRewardTokenCall) {
    this._call = call;
  }
}

export class SetRewardsRedirectCall extends ethereum.Call {
  get inputs(): SetRewardsRedirectCall__Inputs {
    return new SetRewardsRedirectCall__Inputs(this);
  }

  get outputs(): SetRewardsRedirectCall__Outputs {
    return new SetRewardsRedirectCall__Outputs(this);
  }
}

export class SetRewardsRedirectCall__Inputs {
  _call: SetRewardsRedirectCall;

  constructor(call: SetRewardsRedirectCall) {
    this._call = call;
  }

  get account(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get recipient(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class SetRewardsRedirectCall__Outputs {
  _call: SetRewardsRedirectCall;

  constructor(call: SetRewardsRedirectCall) {
    this._call = call;
  }
}
